### ISSUE TITLE
Mach3 hangs when running code

### ISSUE THREAD

**Issue by CamaroRS1** [TimPaterson/Fusion360-Batch-Post#15]
Simple issue.  The first line of code with the filename prevents mach3 from running the code

I simply removed the first line in the gcode file and it runs great.  Thank you so much for this

**Comment by TimPaterson** [comment]
I don't understand how this is a problem.  The filename is a comment, in parentheses.  Isn't it being ignored?

Also, is the suggested tool change G-code OK?  It turns off spindle, turns off coolant, and moves the head to vertical absolute zero.

**Comment by TimPaterson** [comment]
No response, closing issue.
