### ISSUE TITLE
Feature request: Combine setup sheets?

### ISSUE THREAD

**Issue by lutorm** [TimPaterson/Fusion360-Batch-Post#20]
Something that would be super useful is the ability to also combine setup sheets. The setup sheets are really crucial for machines with manual tool changes. Since you are no longer able to generate a setup sheet with several tools in Personal Edition, some way of automatically combining setup sheets from the individual operations would be great.

I realize the output of the setup sheet post processor is HTML and not Gcode, so this probably requires completely new code, but maybe you have insight in how hard this would be.

**Comment by TimPaterson** [comment]
Admitting my inexperience, I don't know what a setup sheet is. When I change tools my machine (Tormach) gives the tool number, and that's enough for me. Anyway, this isn't something I'll be looking at.
