### ISSUE TITLE
Success with TinyG post

### ISSUE THREAD

**Issue by lutorm** [TimPaterson/Fusion360-Batch-Post#21]
You can add the TinyG postprocessor to the success list, I've run this successfilly on my mill. (The only issue I've found is the one I reported in the separate issue where an op without coolant is deleted.)

I use nothing for the tool change code, because I run TinyG through Chilipeppr which can be configured to issue commands when it encounters an M6.

**Comment by TimPaterson** [comment]
Thanks, table has been updated.
