### ISSUE TITLE
Reference Error: X is not defined?

### ISSUE THREAD

**Issue by pip9ball** [TimPaterson/Fusion360-Batch-Post#24]
Is there some options for enabling debugging?

I'm getting the following Error:

0 files were written. 1 Setups were skipped due to error:
Failed on setup [POST] - BUTT_SLEEVE PROJECT FLAT SURFACE: Fusion 360 reported an exception: 3 : ReferenceError: x is not defined
Error at line: 1

I've ensured my setup has XYZ defined correctly and I can post using Fusions built-in Post processor.

I'm using mach3mill.cps for the post.  I've tried supressing all but 1 toolpath to no avail.

![image](https://user-images.githubusercontent.com/5280123/132766944-bd0eedb9-2dcd-41e6-a64d-897094e5fb98.png)

**Comment by TimPaterson** [comment]
Debugging is pretty good using Visual Studio Code, as described here:
https://modthemachine.typepad.com/my_weblog/2019/09/debug-fusion-360-add-ins.html

I think the call to the Fusion 360 API that threw this exception would have occurred on line 951 of PostProcessAll, assuming you've selected "Use individual operations".
