### ISSUE TITLE
Tool change G-code (Txx) not found - When checking "Use Individual Operations"

### ISSUE THREAD

**Issue by Valthol** [TimPaterson/Fusion360-Batch-Post#29]
I use OpenbuildsFusion360PostGrbl.cps post processor. I mainly wanted this plugin to test the rapid movement option. 

Without "Use Individual Operations" everything posts great but it does not involve rapid movement. 

When I check "Use Individual Operations" I get default "M9 G30" for tool change (which I don't intend to use right now) and "M5 M9 M30" for ending sequence and this gives me following error:

0 files were written. 1 Setups were skipped due to error:
Failed on setup Setup2: Tool change G-code (Txx) not found; this post processor is not compatible with Post Process All.

What should I do and where to try this add in without errors? Really eager to test it out! :)

**Comment by cirvladimir** [comment]
I am using Autodesk/.../CAM/cache/posts/grbl.cps and am getting the same error. I do not need any tool change operations and only want rapid movement restored. Should I use a different cps file? Is there another way to just get rapid movement restored?

**Comment by Schalonsus** [comment]
I can confirm they accidentally break "post process all" function with post processor updates.
Same here with the latest linuxcnc.cps.... the latest version from 2022 still works but the latest from 2023 does not

**Comment by TimPaterson** [comment]
I just tried the latest LinuxCNC (EMC2), version 44083 dated 8/14/2023, and it worked fine with `PostProcessAll`.

**Comment by Jutilaje** [comment]
Having this same issue on Mach3Mill Post. I see it says it's compatible, is there a trick to get Mach3Mill post processor to generate tool changes? Thanks!

**Comment by Schalonsus** [comment]
Just download an older version and select it in postprocessall
https://cam.autodesk.com/hsmposts

**Comment by TimPaterson** [comment]
I just downloaded Mach3Mill version 44131 dated 6/14/2024 and it worked fine with `PostProcessAll`.

**Comment by Jutilaje** [comment]
> I just downloaded Mach3Mill version 44131 dated 6/14/2024 and it worked fine with `PostProcessAll`.

That worked perfectly! Thank you!
