### ISSUE TITLE
Files are not getting joined

### ISSUE THREAD

**Issue by Coregas** [TimPaterson/Fusion360-Batch-Post#30]
I am using pikocnc post processor and I have this issue where different operations in one setup are not getting joined.

if I dont check the "use individual operations" the operations are joined but no tool change codes are added.

If I check "use individual operations" only the very first operation is present in the finished file. I can provide the post processor file via email. Please ping me.

I am using the free personal version of Fusion.

I don't get any error messages or anything.

**Comment by TimPaterson** [comment]
With individual operations unchecked, you're just doing Fusion 360's normal post processing on each setup. (The purpose of PostProcessAll in this case is just to do multiple setups.)  You should be getting exactly the same output as running the native Fusion 360 post process command.

When individual operations is selected, it would be interesting to compare the G-code output with PostProcessAll against the output from Fusion 360.  You may have to zip them or change the extension to .txt.

**Comment by TimPaterson** [comment]
I think you just need to change "ending sequence" G-code list to only be G30.  The M9 is messing it up because the post is putting one in just before the tool change. It does mean there will not be an M9 at the end when it's done, so you may have to add it or turn off coolant manually.
