### ISSUE TITLE
Openbuilds CONTROL

### ISSUE THREAD

**Issue by GRVDIGRcorey** [TimPaterson/Fusion360-Batch-Post#31]
Hello, I have everything installed and tried the PP All..... Openbuilds CONTROL didn't like the .nc extension and wants .grbl but once the file is created and opened in CONTROL its blank. What am I missing? Thanks in advance for your time. I really want my rapids back! :(

**Comment by TimPaterson** [comment]
Is this a different post from the one in Issue #29? If so, please attach the .cps (with alternate extension) or include a link to it.

**Comment by GRVDIGRcorey** [comment]
Yes that’s the same one
