### ISSUE TITLE
Matching Base Fusion360 and BatchPost PostProcessor target

### ISSUE THREAD

**Issue by Banchad2** [TimPaterson/Fusion360-Batch-Post#34]
It looks like somehow having the base fusion post menu pointed to a different post than the one the batch post will kick out an error referring to clearance height and refuse to post. Pointing both to the same postprocessor file resolves it and allows posting to finish
![fusionpost error](https://user-images.githubusercontent.com/95944397/145652465-eb3c99b5-d1d3-4e37-b6df-ea6e7ff5967a.jpg)

**Comment by TimPaterson** [comment]
My understanding is you're reporting both a problem and its solution. Thanks, this may be helpful for others in the future.
