### ISSUE TITLE
It appears that I have to post through fusion first in order to get rapid moves restored.

### ISSUE THREAD

**Issue by paramax55** [TimPaterson/Fusion360-Batch-Post#39]
This is not debilitating because I came up with a process that works. And I know I am using this plugin a little differently than what it was originally intended for...

I generate a toolpath with rest machining dependent on previous operations. Then I suppress all of the previous operations so that I only have one operation for post process all to work with. If I use it to restore rapid movements, the "restores" are the same as the original program from fusion - I mean that the commented section is the same as the code that is generated. I have been editing my programs manually and I recognize that the code that is there is the same as what fusion generates.

I found a way around it. I'm not sure if the problem is how I have been posting or not, but I used to generate the toolpath, then click to generate the gcode (button at the upper left), then click the post button at the upper right. I changed that to: generate toolpath, then right click on the toolpath label and select post. Both operations (gcode generation and post) are completed in one step. It's a shortcut. If I do that before I run post process all, I get rapid movements restored. If I run post process all before posting through fusion, I get the modifications that are the same as the original.

Perhaps I would get the restored rapid moves if I simply generated the gcode first? Maybe it doesn't need to post first? I'm willing to experiment, but it takes a really long time. After I suppress an operation, I have to regenerate it after I restore it in order for the following operations to see it for rest machining. Between regenerating things several times, and the length of time for post process all to run, It can easily take an hour to try an option.

**Comment by TimPaterson** [comment]
I don't think I quite understand the situation.  If you could reduce it to a small test case and attach the output, I could look at it.
