### ISSUE TITLE
Post fails (filenotfound) if the setup name has a forwardslash

### ISSUE THREAD

**Issue by amosdudley** [TimPaterson/Fusion360-Batch-Post#58]
The script interprets the / as part of the filepath, and spits a file not found error. So, you can't name a Setup "1/8 End Mill" for example and then post using this script.

Not a major issue, but it might be helpful for someone if a note about this were in the Readme.

**Comment by TimPaterson** [comment]
The documentation starts right off saying the name of the setup is used as a file name.  It didn't seem necessary to then say you should choose a name that is valid as a file name, but I suppose that could be added.
