### ISSUE TITLE
'Preserve order' in Pattern not respected

### ISSUE THREAD

**Issue by teckwee** [TimPaterson/Fusion360-Batch-Post#67]
I used Patterns quite extensively recently and notice that the 'Preserve order' has different behavior in some designs. 

Essentially, the output for 'Preserve order' and 'Order by operation' is the same even though the former is clearly what I want when I simulated the operation. 

![Screenshot 2024-02-16 180205](https://github.com/TimPaterson/Fusion360-Batch-Post/assets/10190167/dae89d13-64d6-490d-8a89-536eb7dfbb8a)

Happy to provide files and info if required. Thank you so much.

**Comment by teckwee** [comment]
Sorry I just saw this... should have searched before - https://github.com/TimPaterson/Fusion360-Batch-Post/discussions/36

Is anyone aware of any updates? I'm pretty sure it works in one of our design.

**Comment by TimPaterson** [comment]
There is no new information on this.
