### ISSUE TITLE
FAILED to Run  "C:/Users/livnp/Desktop/POST ALL FUSION/PostProcessAll.py", line 184, in InitAddIn 

### ISSUE THREAD

**Issue by confused1234** [TimPaterson/Fusion360-Batch-Post#75]
I bought a new windows 11 laptop and went to install and use the PostAll and I get this run error?
![postall](https://github.com/user-attachments/assets/b63dae01-fb51-4244-9868-7defd211ec86)

**Comment by TimPaterson** [comment]
Did you include the `resources` folder?

**Comment by TimPaterson** [comment]
Fusion isn't finding it, so make sure you have the folder structure complete.

**Comment by confused1234** [comment]
deleted and started over, it works like a champ now! thank you once again!!
